src/components/edit-asset-address-form/editable-address/editable-address.tsx

Bug fix: if the asset being edited has a version of 0 (this is a value of type Number), this is seen as falsy, and so it triggers the invalid version error. However 0 is a valid version value.
The asset version is now converted to a string. 
Number 0.toString() = "0" (Truthy)
null / undefined .toString() = throws error

MR-692 - Asset invalid version check bug fix

---

src/components/edit-asset-address-form/editable-address/editable-address.tsx
src/components/edit-asset-address-form/reference-address/reference-address.tsx
src/components/edit-asset-address-form/styles.scss
src/views/asset-edit-view/__snapshots__/asset-edit-view.test.tsx.snap

REFERENCE ADDRESS FIELDS:
ReferenceAddress readonly fields now look lighter, as disabled field should look.
PATCH ASSET VERSION VALIDATION REMOVED:
After numerous tests with Postman, we've established that sending a 'null' asset version works fine with the way Asset API is set up currently.
The Asset, that initially has a versionNumber of 'null', now gets PATCH'ed correctly when sending 'null' into patchAsset, and its versionNumber gets then updated automatically to a value of 0 (by DynamoDb)

MR-692 - ReferenceAddress fields visually lighter (looking more "disabled") and removed Asset version check

---

yarn.lock

Updated yarn lock file with newest version of common. 
Prior to this PR, this repo was implementing the older version of patchAsset (API call from common) which would only accept a 'string' for assetVersion.
'common' has been updated so that assetVersion can either be a string, or null, and this caused a typescript issue.
For more info see PR - https://github.com/LBHackney-IT/mtfh-frontend-common/pull/237

MR-692 - Updated yarn lock file with newest version of common

---

.circleci/config.yml
jest.config.js
src/components/cautionary-alerts-details/cautionary-alerts-details.test.tsx
src/components/cautionary-alerts-details/cautionary-alerts-details.tsx
src/views/asset-view/asset-view.test.tsx
webpack.config.js

Cautionary alerts on the system are showing inaccurate person and alert information, so we are temporarily showing links to the cautionary alerts spreadsheet to give officers more accurate information.
Will need to do this as well on the personal-details page, as that has the same issue.
--
This PR is made to address partly inaccurate CA information displayed on the FE UI. We know for a fact that if CA is being displayed, then it deserves to be displayed. The problem is the details about the CA since most CAs are being displayed on incorrect people (has to do with person guids being swapped around between CA records for some reason).
So this PR as mentioned is only a temporary hotfix that will get rolled back whenever the data source corruption issue gets resolved. So all the commented …

Link ca spreadsheet instead of alerts

---

src/components/cautionary-alerts-details/cautionary-alerts-details.test.tsx
yarn.lock

Copy of PR #56 which failed to deploy to development potentially because the 'common' commit hash reference it was using was not the latest. 
https://app.circleci.com/pipelines/github/LBHackney-IT/mtfh-frontend-property/297/workflows/fd45e188-b11a-44ce-ac7b-04a94d70e7c6/jobs/1021
PR #56 description:
If you run all MMH MFEs, 'main' branch if each one, 'property' should throw the below error.
There is an issue with the `alerts` object that's being passed into the component CautionaryAlertsDetails, in `cautionary-alerts-details.test.tsx`
NOTE: after checking with Adam T, the `skip` keyword is to be left there for the two tests for the time being, as team powerhouse is working on a cautionary alert related fix.
The 'base' alert used now implements the Alert interface (from 'common') and I've …

Fixed issue with assets used in cautionary alerts details tests - Updated 'Common' commit hash in Yarn.Lock

---

.circleci/config.yml
jest.config.js
src/components/cautionary-alerts-details/cautionary-alerts-details.test.tsx
src/components/cautionary-alerts-details/cautionary-alerts-details.tsx
src/views/asset-view/asset-view.test.tsx
webpack.config.js

As mentioned in this PR, there was a CA data issue hence we applied a temporary fix to provide the users with the CA spreadsheet. The majority of the data has now been fixed hence we would like to get rid of the temporary fix and show the users the CA from the API like it was before.

reverted CA changes so you can see CA Alert from API

---

src/components/edit-asset-address-form/editable-address/editable-address.tsx
src/components/edit-asset-address-form/editable-address/types.ts
src/components/edit-asset-address-form/editable-address/utils.ts
src/views/asset-edit-view/asset-edit-view.test.tsx
src/views/asset-edit-view/asset-edit-view.tsx
src/views/asset-edit-view/layout.tsx
yarn.lock

- There is a sub-object in Tenure which contains information about the tenured asset
- This needs to be updated when the Asset is updated
- Add call to retrieve Tenure (necessary to find ETAG)
- Add call to update Tenure
- Added `utils.ts` file to break up code
- Added `types.ts` file to enable reuse of `PatchAssetFormValues`
- Moved both patch requests into `Promise.All()` block to reuse success and error logic

Add call to change tenure

---

src/components/new-asset-form/new-asset.tsx
src/components/new-asset-form/schema.ts
src/components/new-asset-form/utils/area-office-names.tsx
src/components/new-asset-form/utils/managing-organisations.tsx
src/factories/requestFactory.ts
src/views/new-asset-view/__snapshots__/new-asset-view.test.tsx.snap

Added new _Post Preamble_ optional field field in Address section
Existing field _Area Office Name_ has been changed from a string field to a drop down field, populated by a set of options. These options come from a [spreadsheet](https://docs.google.com/spreadsheets/d/1sMPVkcKEBUpCS8ALcAQ_IZp8q0RT3eXb/edit#gid=431043573) and they are hardcoded in `area-office-names.tsx`

Add Asset - New post preamble optional field & existing area office name field changed from string input to dropdown

---

src/components/new-asset-form/new-asset.tsx
src/components/new-asset-form/schema.ts
src/components/new-asset-form/styles.scss
src/factories/requestFactory.ts
src/views/new-asset-view/__snapshots__/new-asset-view.test.tsx.snap
src/views/new-asset-view/layout.tsx

Following the [feedback ](https://docs.google.com/document/d/1hm26uKZF-tlBBJhl7BLfSy1CLeWxMwfD82JlYgTpMy4/edit)after the first round of testing this feature, I've applied the following changes.
- Moved "Asset details" section under "Address" section - [Screenshot](https://github.com/LBHackney-IT/mtfh-frontend-property/assets/70756861/b18d7105-bb12-419e-a83d-b4d858b4c54c)
- Moved "Patches" field after "Area office name" field - [Screenshot](https://github.com/LBHackney-IT/mtfh-frontend-property/assets/70756861/695e7f08-16dd-43c8-88cd-fb2a38f409a8)
- Added disclaimer under "New Property" heading to make users aware they have the power to input incorrect data - [Screenshot](https://github.com/LBHackney-IT/mtfh-frontend-property/assets/70756861/a9c2c83b-420c-4a64-b7b5-7fb57e32b655)
- Removed …

MR-698 - New Asset post-feedback changes

---

src/components/property-tree/property-tree-utils.tsx
src/components/property-tree/property-tree.tsx

For some assets, when `treeViewData` (in `addParentsAndPrinciple()`) ended up being equal to an empty array, an empty box would show, instead of showing the asset by itself:
A slight change in the logic fixed the issue:
Once we managed to retrieve children assets, I noticed these would not always be displayed. If you reloaded the page 20 times, sometimes they would appear and some other times they would not.
This was due to the fact that `childNodes` was not part of `PropertyTree`'s state, but it was just variable, defined once. Refactored `PropertyTree` component by adding a second `useEffect` hook and modifying the original one.

MR-708 - Fix bugs: (1) Empty box shown instead of asset hierarchy (2) ChildrenAssets sometimes do not render

---

src/components/asset-sidebar/index.tsx
src/components/edit-asset-address-form/editable-address/editable-address.tsx
src/components/edit-asset-address-form/editable-address/form-action-buttons.tsx
src/components/edit-asset-address-form/editable-address/utils.ts
src/components/edit-asset-address-form/reference-address/reference-address.tsx
src/views/asset-edit-view/__snapshots__/asset-edit-view.test.tsx.snap
src/views/asset-edit-view/asset-edit-view.test.tsx
src/views/asset-edit-view/layout.tsx

- Asset View now displays "Edit address details" button regardless of whether the asset has a UPRN or not
- If the asset has a UPRN, nothing changes, usual behaviour.
- If the asset does not have a UPRN, only one set of editable fields are shown in the "Edit address" page. These are pre-filled with current address details (as in this case no LLPG request is fired).
**Changed behaviour when the LLPG request fails**
When we entered the "Edit address" page previously, for an asset with a UPRN, if the LLPG request failed, we would display the current address read-only fields (on the right) and on the left, we'd display all editable address fields, but blank. This behaviour has been changed to be similar to the non-UPRN edit, meaning that if the LLPG request fails, the read-only "current …

MR-733 - Allow address edit of assets with no UPRN 

---

src/views/asset-edit-view/asset-edit-view.tsx

Removed Asset Type limitation, which was causing non Dwelling/LettableNonDwelling properties not to load in Edit Address page

MR-733 - Removed Asset Type limitation from view

---

src/components/inline-asset-search/inline-asset-search.tsx
src/components/new-asset-form/new-asset.tsx
src/components/new-asset-form/patches-field.tsx
src/components/new-asset-form/schema.ts
src/factories/requestFactory.ts
src/views/new-asset-view/__snapshots__/new-asset-view.test.tsx.snap
src/views/new-asset-view/layout.tsx
src/views/related-assets-view/__snapshots__/related-assets-view.test.tsx.snap
src/views/related-assets-view/layout.tsx
src/views/related-assets-view/utils.ts
yarn.lock

**Issue:**
Prior to this PR, "Edit address" feature would allow the user to **optionally** add up to 2 parents, specifically "Estate" and "Block". Once these related asset were added using the form, these would eventually populate the `asset.parentAssetIds` field of the new asset with one or more GUIDs (separated by `#`).
**Resolution:** 
"Estate" and "Block" fields, which where conditionally shown (based on the asset type being added), have been replaced by one (still optional) "Parent asset" field, which is always visible. This allows the user to link the asset that's being created, to one single parent asset (of any asset type).
Now not only the field `asset.parentAssetIds` is updated, with one single GUID belonging to the chosen parent asset, but the parent asset is also added to the …

MR-734 - New Asset form - Only one parent asset can be added to a new asset

---

src/components/new-asset-form/new-asset.tsx
src/components/new-asset-form/schema.ts
src/factories/requestFactory.ts
src/views/new-asset-view/__snapshots__/new-asset-view.test.tsx.snap

Jira: https://hackney.atlassian.net/browse/MR-516
- When adding properties, we'd like to know whether we can add the default DLO contracts to them
- Backend implementation TBC but ideally it would form part of the SNS message, listened to by Asset listener and migrated in to RH DB
- The request generator is well tested already, updating the snapshot will do for this

MR-516 Add option to add default SOR contracts

---

src/components/related-assets/utils.ts

In the related asset page, assetTypes were not sorted. Sometimes the order changed between renders.
- Add sorting to assetType (alphabetical, dwelling last)

Sort assetType alphabetically in related assets page

---

src/components/inline-asset-search/inline-asset-search.tsx
src/components/inline-search-form/inline-search-form.tsx
src/views/new-asset-view/__snapshots__/new-asset-view.test.tsx.snap

Production bug: creating a new asset with a parent asset is not possible. The form does not submit.
Error:
Problem:
Following PR (#103) the above issue was introduced. Maybe not enough testing was done after merging as this was just a "refactoring PR".
Currently (in production) when a user selects a parent asset, in the New Asset form, what is actually selected "behind the scenes" is only parent asset ID. This was ok back when all we needed was just the `parentAssetId`, but now we also need to select the whole asset as it to finally populate the `asset.assetLocation.parentAssets` field.
Work done:
- reverted one of the changes of PR #103 (main fix)
- added test IDs to be referenced in E2E test repo (I have incorporated the selection of the parent asset in 2 E2E tests)

Production bug fix - Cannot create new asset with parent asset

---

src/components/patch-assignment-form/patch-assignment-form.tsx

Some patches can be vacant hence the name and email address should be nullable.

nullable email address

---

src/components/edit-asset-ownership-form/edit-asset-ownership-form.tsx
src/components/lbh-ownership-information/lbh-ownership-information.tsx

This ensures that the property page continues to load in the extremely rare case that the assetManagement field is undefined.
This change is being made to resolve a recently reported production issue affecting a small subset of properties

Handle undefined assetManagement field

---

.circleci/config.yml
src/components/new-asset-form/new-asset.tsx
src/components/new-asset-form/schema.ts
src/factories/requestFactory.ts
src/views/new-asset-view/__snapshots__/new-asset-view.test.tsx.snap
yarn.lock

- Added a field to the form to capture the rent group information whilst creating an Asset via 'New Property' form.
- Upgrade CircleCI 'sonarsource/sonarcloud' orb version from v1.0.3 to v2.0.0.
- Added separate CCI executor for the Sonar Scan & separated the scan into a separate job.
We have the MMH system for managing Assets and Tenancies separate from the HFS system managing the finance side of this. It so happens that the HFS system needs part of the data that is now being managed by the MMH. It's not practical for HFS system to access MMH system data for the financial and reporting operations that it needs. As such a sync of that kind of data is needed. Currently it is done by a semi-automatic process that involves copying whatever was inputted into MMH into GDrive spreadsheet that …

Added 'Rent Group' field to the 'New Property' form.

---

src/components/new-asset-form/new-asset.tsx
src/components/new-asset-form/schema.ts
src/factories/requestFactory.ts
src/views/new-asset-view/__snapshots__/new-asset-view.test.tsx.snap
yarn.lock

- Made the 'Rent Group' select options show Rent Group code descriptions in addition to the codes themselves.
- There are a couple of user groups that _are/may_ be using the form. Not all of them are familiar with the Rent Group codes as not all of them have been involved in finance as much others.
- Updated the schema as the 'rentGroup' cannot become nullable - it's either a string, or undefined.
- Also had to make some changes within the request mapper for to take into account the 'RentGroup' values are no longer codes.
- This PR extends the PR #128 .
- Uses `mtfh-fronted-common` version: PR [#292](https://github.com/LBHackney-IT/mtfh-frontend-common/pull/292), which is an extension of PR [#291](https://github.com/LBHackney-IT/mtfh-frontend-common/pull/291).
| <img …

Add better 'RentGroup' code descriptions to the New Property form.

---

src/components/patch-details/patch-details.test.tsx
src/components/patch-details/patch-details.tsx

Update `PatchDetails` component to handle cases where responsible entities is empty (e.g. here - https://manage-my-home-development.hackney.gov.uk/property/5aca3cdd-5e00-b0f5-ca19-cb219a832199)

Fix error if patch or area responsible entities are empty
